export const partnerLogos = [
  { name: "H&M", file: "hm", w: 142, h: 99 },
  { name: "C&A", file: "cna", w: 125, h: 99 },
  { name: "PUMA", file: "puma", w: 191, h: 102 },
  { name: "GUESS", file: "guess", w: 122, h: 107 },
  { name: "ZARA", file: "zara", w: 199, h: 91 },
  { name: "HUGO BOSS", file: "boss", w: 229, h: 93 },
  { name: "next", file: "next", w: 148, h: 52 },
  { name: "LPP", file: "lpp", w: 132, h: 58 },
  { name: "BESTSELLER", file: "bestseller", w: 236, h: 68 },
  { name: "COLIN'S", file: "colins", w: 176, h: 55 },
  { name: "NEW YORKER", file: "newyorker", w: 205, h: 58 },
  { name: "TOM TAILOR", file: "tomtailor", w: 241, h: 71 },
  { name: "Terranova", file: "terranova", w: 208, h: 34 },
  { name: "OVS", file: "ovs", w: 164, h: 73 },
  { name: "women'secret", file: "womensecret", w: 271, h: 40 },
  { name: "G-STAR RAW", file: "graw", w: 103, h: 123 },
  { name: "Betty Barclay", file: "bettybarclay", w: 262, h: 84 },
] as const;
